name: Download from Google Drive
on:
  push:
    branches:
      - main
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Acquire Google access token
        id: google-access-token
        uses: playeveryware/action-google-access-token@v1
        with:
          credentials: ${{ secrets.YOUR_SERVICE_ACCOUNT_CREDENTIALS }}
          scope: 'https://drive.google.com/drive/folders/1AOZRyAV1FRSkfBMuvc52McccUJqjgbZF?dmr=1&ec=wgc-drive-globalnav-goto'
      - name: Download file
        uses: pew-actions/google-drive-download@v1
        with:
          token: ${{ steps.google-access-token.outputs.token }}
          file-id: 1AOZRyAV1FRSkfBMuvc52McccUJqjgbZF
          path: ./files
      - name: Show file information
        run: ls ./files
