name: Download Google Drive File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Google Drive file
        uses: actions/download-artifact@v2
        with:
          name: google-drive-file
          path: ./files
          google_drive_key: ${{ secrets.GOOGLE_DRIVE_KEY }}
          google_drive_id: ${{ secrets.GOOGLE_DRIVE_ID }}
